version: '3.8'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_DATABASE: restaurante_database
      MYSQL_USER: root
      MYSQL_PASSWORD: ''
    ports:
      - "3306:3306"

